name: sle_seller
description: 'A new Flutter project.'
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  fluttertoast: ^8.2.8
  flutter_inset_box_shadow: ^1.0.8
  url_launcher: ^6.3.1
  flutter_riverpod: ^2.6.1
  animated_custom_dropdown: ^3.1.1
  http: ^1.2.2
  shared_preferences: ^2.3.2
  flutter_dotenv: ^5.2.1
  shimmer: ^3.0.0
  firebase_storage: ^12.3.5
  image_picker: ^1.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - lib/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.otf
    - family: great-vibes
      fonts:
        - asset: assets/fonts/GreatVibes-Regular.otf
