// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHESddz8aA6nRPxFHPFgsBFBhoomcuf50',
    appId: '1:21882547294:web:87ecfab5884fa51a8058cf',
    messagingSenderId: '21882547294',
    projectId: 'all-in-one-3bdcb',
    authDomain: 'all-in-one-3bdcb.firebaseapp.com',
    storageBucket: 'all-in-one-3bdcb.appspot.com',
    measurementId: 'G-BJ4TJBSCT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiA-j1ap3dwN7A3pfaUUmH-uFogaOeHsQ',
    appId: '1:21882547294:android:b1262324dcd8ea3e8058cf',
    messagingSenderId: '21882547294',
    projectId: 'all-in-one-3bdcb',
    storageBucket: 'all-in-one-3bdcb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9y3iGS2Xk3HngivFIUJi7Dj0zwZit3ys',
    appId: '1:21882547294:ios:89647fb5b59adf988058cf',
    messagingSenderId: '21882547294',
    projectId: 'all-in-one-3bdcb',
    storageBucket: 'all-in-one-3bdcb.appspot.com',
    iosBundleId: 'com.example.sleSeller',
  );
}
